name: islamiapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  animated_custom_dropdown: ^3.1.1
  dio:
  provider: ^6.1.2
  dartz:
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/Files/

  fonts:
    - family: El Messiri
      fonts:
        - asset: assets/fonts/ElMessiri-Bold.ttf
        - asset: assets/fonts/ElMessiri-Medium.ttf
        - asset: assets/fonts/ElMessiri-Regular.ttf
        - asset: assets/fonts/ElMessiri-SemiBold.ttf
